options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_32

substitutions:
  _ARTIFACT_MODE: "full"

steps:
  - name: 'gcr.io/cloud-builders/git'
    id: Get Short SHA
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "SHORT_SHA=$SHORT_SHA" >> /workspace/commit.env

  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Login
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login --username=$$DOCKER_USERNAME --password=$$DOCKER_PASSWORD
    secretEnv:
      - 'DOCKER_USERNAME'
      - 'DOCKER_PASSWORD'

  - name: 'gcr.io/cloud-builders/docker'
    id: Build & Push (buildx)
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        source /workspace/commit.env

        # Create or reuse buildx builder
        docker buildx create --use --name cbuilder || docker buildx use cbuilder

        docker buildx build \
          --platform=linux/amd64 \
          --progress=plain \
          --pull \
          --build-arg ARTIFACT_MODE=${_ARTIFACT_MODE} \
          --cache-from=type=registry,ref=docker.io/$$DOCKER_USERNAME/lind-wasm-apps:buildcache \
          --cache-to=type=registry,ref=docker.io/$$DOCKER_USERNAME/lind-wasm-apps:buildcache,mode=max \
          -t docker.io/$$DOCKER_USERNAME/lind-wasm-apps:latest \
          -t docker.io/$$DOCKER_USERNAME/lind-wasm-apps:sha-$SHORT_SHA \
          --push \
          .
    secretEnv:
      - 'DOCKER_USERNAME'

availableSecrets:
  secretManager:
    - versionName: projects/x-micron-451502-m7/secrets/docker-username/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/x-micron-451502-m7/secrets/docker-password/versions/latest
      env: 'DOCKER_PASSWORD'