#!/usr/bin/env bash
set -euo pipefail

# Toolchain paths
CLANG="/home/lind/lind-wasm/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04/bin/clang"
WASM_OPT="/home/lind/lind-wasm/tools/binaryen/bin/wasm-opt"
WASMTIME="/home/lind/lind-wasm/src/wasmtime/target/debug/wasmtime"

# Bash source root = directory of this script
BASH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sysroot and output dir (both under bash/)
SYSROOT="$BASH_ROOT/sysroot_overlay"
OUT_DIR="$BASH_ROOT/out_wasm"

# Existing glibc WASI sysroot (has libc.a, crt1.o, headers, etc.)
GLIBC_SYSROOT="/home/lind/lind-wasm/src/glibc/sysroot"

mkdir -p "$OUT_DIR"
cd "$BASH_ROOT"

echo "BASH_ROOT     = $BASH_ROOT"
echo "SYSROOT       = $SYSROOT"
echo "GLIBC_SYSROOT = $GLIBC_SYSROOT"
echo

# 1) Ensure sysroot_overlay exists and is populated from glibc sysroot
if [ ! -d "$SYSROOT" ]; then
    echo "sysroot_overlay not found, creating from GLIBC_SYSROOT..."

    if [ ! -d "$GLIBC_SYSROOT" ]; then
        echo "Error: GLIBC_SYSROOT '$GLIBC_SYSROOT' does not exist."
        exit 1
    fi

    mkdir -p "$SYSROOT"
    cp -a "$GLIBC_SYSROOT/." "$SYSROOT/"
    echo "sysroot_overlay created at: $SYSROOT"
    echo
fi

# 2) Need an existing Makefile (generated by native ./configure)
if [ ! -f Makefile ]; then
    echo "Error: Makefile not found."
    echo "Run this once (native, not WASM):"
    echo "  ./configure --without-bash-malloc --disable-nls --disable-profiling"
    exit 1
fi

# 3) WASM compiler flags — Makefile knows what to build, we just switch CC/CFLAGS/LDFLAGS
CC_WASM="$CLANG --target=wasm32-unknown-wasi --sysroot=$SYSROOT"
CFLAGS_WASM="-O2 -g"
LDFLAGS_WASM="-Wl,--import-memory,--export-memory,--max-memory=67108864,\
--export=__stack_pointer,--export=__stack_low"

echo "Using:"
echo "  CC      = $CC_WASM"
echo "  CFLAGS  = $CFLAGS_WASM"
echo "  LDFLAGS = $LDFLAGS_WASM"
echo

echo "Running make clean..."
make clean || true

echo "Building bash with WASM toolchain via Makefile..."
make -j1 \
    CC="$CC_WASM" \
    CFLAGS="$CFLAGS_WASM" \
    LDFLAGS="$LDFLAGS_WASM"

# 4) Check if bash exists
if [ ! -f bash ]; then
    echo "Error: bash binary not found after build."
    echo "Please scroll up and check the last linker error from make."
    exit 1
fi

echo
echo "file bash:"
file bash || true
echo

# 5) If bash is WebAssembly, treat it as the wasm module
if ! file bash | grep -qi "WebAssembly"; then
    echo "Warning: 'bash' is not reported as WebAssembly. Something is off."
    echo "You can still run 'file bash' manually and inspect the output."
    exit 1
fi

RAW_WASM="$OUT_DIR/bash.wasm"
OPT_WASM="$OUT_DIR/bash.opt.wasm"
CWA_FILE="$OUT_DIR/bash.cwasm"

echo "Copying bash -> $RAW_WASM"
cp bash "$RAW_WASM"

echo "Running wasm-opt..."
"$WASM_OPT" --epoch-injection --asyncify -O2 --debuginfo \
    "$RAW_WASM" -o "$OPT_WASM"

echo "Producing cwasm with wasmtime..."
"$WASMTIME" compile "$OPT_WASM" -o "$CWA_FILE"

echo
echo "Build complete. Files in $OUT_DIR:"
ls -lh "$OUT_DIR"
